apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: inboxhire
  labels:
    name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  template:
    metadata:
      labels:
        service: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        volumeMounts:
        - name: postgres-volume-mount
          mountPath: /var/lib/postgresql/data
          subPath: postgres
        env:
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: inboxhire-config
                key: DB_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: inboxhire-secret
                key: DB_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: inboxhire-config
                key: DB_NAME
      restartPolicy: Always
      volumes:
      - name: postgres-volume-mount
        persistentVolumeClaim:
          claimName: postgres-pvc