apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: inboxhire
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: iusmanq/inboxhire-api:latest
          ports:
            - containerPort: 3002
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: inboxhire-config
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: inboxhire-config
                  key: DB_PORT
            - name: DB_USER
              valueFrom:
                configMapKeyRef:
                  name: inboxhire-config
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: inboxhire-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              valueFrom: 
                configMapKeyRef:
                  name: inboxhire-config
                  key: DB_NAME