apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: inboxhire-ingress
  namespace: inboxhire
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
    traefik.ingress.kubernetes.io/router.middlewares: inboxhire-strip-api@kubernetescrd
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: 3002
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api
  namespace: inboxhire
spec:
  stripPrefix:
    prefixes:
      - /api
